Chore/practice-js
Atlantis-Academy/react-learn-ikorol pull request #6
Opened 2020-11-19 19:19 UTC by ikorol3107

Выполнены практические задания из таска "[Practice JS basics (part 1-2)](https://github.com/Atlantis-Academy/react-learn-ikorol/issues/5#issue-746027701)"

2020-11-19 19:20 UTC, TorinAsakura commented
@ikorol3107 линк к задачам создаётся лишь посредством указания якоря #номер

2020-11-20 12:03 UTC, TorinAsakura requested changes

2020-11-20 12:03 UTC, TorinAsakura commented on index.html
> +</html>
last line warn

2020-11-20 12:03 UTC, TorinAsakura commented on js/task1.js
> +console.log(personalMovieDB);
the same

2020-11-20 12:03 UTC, TorinAsakura commented on js/task2.js
> +console.log(personalMovieDB);
the same

2020-11-20 12:03 UTC, TorinAsakura commented on js/task2.js
> +// } while( b < 2);
Если ты готовишь код к слиянию (merge) код должен быть чистым, представь, что с ним будут работать другие члены команды. Закомментированные шлейфы кода неприемлемы в ПРах которые направлены в master

2020-11-20 12:03 UTC, TorinAsakura commented on js/task2.js
> +//Используйте код с предыдущего урока
Выноси пожалуйста это в README в формате markdown

2020-11-23 12:28 UTC, TorinAsakura requested changes

2020-11-23 12:28 UTC, TorinAsakura commented on .gitignore
> +yarn-error.log*
А просто указать маску для файлов формата log? Не?

2020-11-23 12:28 UTC, TorinAsakura commented on js/task1.js
>  "Use strict";
для каких целей ты используешь строгий режим?

2020-11-23 12:28 UTC, TorinAsakura commented on js/task2.js
> +let a = 0;
почему let, а не const?

2020-11-23 16:54 UTC, ikorol3107 commented on .gitignore
> +yarn-error.log*
да, согласна. Переделаю.

2020-11-23 16:54 UTC, ikorol3107 commented on js/task1.js
>  "Use strict";
как доп.контроль для избегания ошибок при написании кода

2020-11-23 16:54 UTC, ikorol3107 commented on js/task2.js
> +let a = 0;
потому-что использую в цикле, где значение переменной заведомо будет меняться, а const не меняется.

2020-11-23 16:57 UTC, TorinAsakura commented on js/task1.js
>  "Use strict";
Для этого нужно использоваться  typecheck, eslint

2020-11-24 08:26 UTC, TorinAsakura commented
@ikorol3107 теперь приведи свои коммиты в порядок, главный критерий порядка - осознанность = понятность
Сейчас у тебя в коммит-стори царит хаос, где-то опечатка, а где-то шаблонная копипаста. Это недопустимо. Я уже вроде объяснял что да как

2020-11-27 10:18 UTC, TorinAsakura approved these changes

2020-11-27 10:18 UTC, merged